version: '3.8'

services:
  nginx:
    build: .
    container_name: nginx
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./letsencrypt/etc:/etc/letsencrypt:ro
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf:ro
