version: '3.8'

services:
  nginx:
    build:
      context: .
      args:
        - REACT_APP_CONTACT_EMAIL=${REACT_APP_CONTACT_EMAIL}
    container_name: nginx
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./letsencrypt/etc:/etc/letsencrypt:ro
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/html/.well-known/acme-challenge:rw
    env_file:
      - .env
    networks:
      - web-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./letsencrypt/etc:/etc/letsencrypt:rw
      - ./certbot/www:/var/www/html/.well-known/acme-challenge:rw
    depends_on:
      - nginx
    networks:
      - web-network
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  web-network:
    driver: bridge
