version: '3.8'

services:
  personal-site:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: personal-site
    restart: unless-stopped

    # Security options
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /var/run
      - /var/cache/nginx

    # Resource limits to prevent resource exhaustion
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M

    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    networks:
      - traefik-public

    labels:
      - "traefik.enable=true"

      # Router configuration
      - "traefik.http.routers.personal-site.rule=Host(`gopee.dev`) || Host(`www.gopee.dev`)"
      - "traefik.http.routers.personal-site.entrypoints=websecure"
      - "traefik.http.routers.personal-site.tls.certresolver=letsencrypt"

      # Service configuration
      - "traefik.http.services.personal-site.loadbalancer.server.port=80"

      # Health check
      - "traefik.http.services.personal-site.loadbalancer.healthcheck.path=/"
      - "traefik.http.services.personal-site.loadbalancer.healthcheck.interval=30s"
      - "traefik.http.services.personal-site.loadbalancer.healthcheck.timeout=10s"

      # WWW redirect middleware
      - "traefik.http.middlewares.www-redirect.redirectregex.regex=^https://www\\.gopee\\.dev/(.*)"
      - "traefik.http.middlewares.www-redirect.redirectregex.replacement=https://gopee.dev/$${1}"
      - "traefik.http.middlewares.www-redirect.redirectregex.permanent=true"

      # Apply ALL security middlewares
      - "traefik.http.routers.personal-site.middlewares=security-headers@file,compression@file,rate-limit-general@file,in-flight-req@file,slow-loris-protection@file,bot-protection@file,www-redirect"

networks:
  traefik-public:
    external: true
